ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure('2') do |config|

  config.vm.define :provisioner do |provisioner|
    provisioner.vm.box = 'generic/ubuntu1804'
    provisioner.vm.hostname = 'provisioner'
    provisioner.vm.synced_folder '../../', '/vagrant' # , type: 'rsync'
    provisioner.vm.network :private_network,
                           virtualbox__intnet: "tink_network",
                           auto_config: false
    provisioner.vm.provision :shell,
                             path: 'tinkerbell.sh'

    provisioner.vm.provider :virtualbox do |vb|
      vb.memory = 2*1024
      vb.cpus = 2
    end
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = 'generic/alpine38'
    worker.vm.boot_timeout = 10
    worker.vm.provider :virtualbox do |vb|
      vb.memory = 1*1024
      vb.cpus = 1
      vb.gui = true
      vb.customize [
        'modifyvm', :id,
        '--nic1', 'intnet',
        '--intnet1', 'tink_network',
        '--boot1', 'net',
        '--boot2', 'none',
        '--boot3', 'none',
        '--boot4', 'none',
        '--macaddress1', '080027000001'
      ]
    end
    worker.vm.network :private_network,
                      virtualbox__intnet: "tink_network",
                      auto_config: false
  end

end
